export const PlayerActionTypes = {
  PLAY: "PLAY",
  PAUSE: "PAUSE",
  SET_ACTIVE: "SET_ACTIVE",
  SET_DURATION: "SET_DURATION",
  SET_CURRENT_TIME: "SET_CURRENT_TIME",
  SET_VOLUME: "SET_VOLUME",
};
